name: city-emergency
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - pytorch>=1.10.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - pillow>=9.0.0
  - pip:
    - gymnasium>=0.28.0
    - -e . 